services:
  - type: web
    name: webhook-server
    env: python
    buildCommand: pip install -r requirements.txt\
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: NOTION_TOKEN
        value: あとでRenderで設定
      - key: NOTION_DATABASE_ID
        value: あとでRenderで設定
